spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: false

# Spring-dotenv: czytaj .env z głównego katalogu projektu
env:
  directory: ../
