server:
  port: 8086

spring:
  application:
    name: payment_service

  datasource:
    url: jdbc:postgresql://localhost:5433/electric_shop_db
    username: electric_user
    password: electric_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true # Warto ustawi? na true przy debugowaniu
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: payments  # <--- POPRAWKA (by?o orders)

  # --- KAFKA CONFIGURATION ---
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    # Producer (Wysy?amy PaymentSucceededEvent jako JSON)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    # Consumer (Odbieramy OrderCreatedEvent jako JSON)
    consumer:
      group-id: payment-service-group # Wa?ne: unikalne ID grupy
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: payment_schema_version
    schemas: payments
    default-schema: payments # <--- POPRAWKA (by?o orders)
    create-schemas: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

stripe:
  api-key: {STRIPE_API_KEY:test_stripe_api_key}