spring:
  application:
    name: cart-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
          # Klucz wiadomości to String (np. userId) - to jest OK
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

          # ZMIANA: Wartość to Obiekt, więc musimy użyć JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
            # Dodajemy nagłówek z typem, żeby Consumer wiedział co odczytać
        spring.json.add.type.headers: true

  #  Thread Pool     Configuration
  threads:
    virtual:
      enabled: true

# Fallback configuration (used when Config Server is unavailable)
server:
  port: 8084

spring.data.redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

grpc:
  client:
    product-service:
      address: ${GRPC_CLIENT_PRODUCT_SERVICE_ADDRESS:static://localhost:9090}
      negotiation-type: plaintext
